[package]
name = "pomodoro-tui"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "A simple Pomodoro timer with a terminal user interface."
homepage = "https://github.com/iman1704/pomodoro-tui"
repository = "https://github.com/iman1704/pomodoro-tui"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.29.0"
tui-big-text = "0.7.1"
